### ISSUE TITLE
No longer compiles with GRDB 4.1.0

### ISSUE THREAD

**Issue by AndyHeardApps** [RxSwiftCommunity/RxGRDB#56]
With the release of GRDB 4.1.0 a few days ago, the framework seems to no longer compile, with an error in `ValueObservation+Rx.swift` on line 17 saying:

`Type 'ValueObservation<Reducer>' does not conform to protocol '_ValueObservationProtocol'`

The prompt attempts to insert the `func start(i: _, onError: _, onChange: _)` defined in the `_ValueObservationProtocol`. This protocol requirement appears to mirror a similar function in GRDB found in `ValueObservation.swift` which was updated with the release of `4.1.0` to no longer throw an error, which looks to have broken protocol conformance.

**Comment by groue** [comment]
Hello @AndyHeardApps,

Yes, I'm very sorry about this issue.

It can't publish #55, which fixes this compilation error, until GRDB 4.1.0 is available on CocoaPods. Unfortunately, this is blocked by https://github.com/CocoaPods/CocoaPods/issues/8925.

You have two options:

1. Downgrade GRDB to v4.0.1
2. Use GRDB v4.1.0, and RxRGDB from https://github.com/groue/RxGRDB, branch `dev/async`.

**Comment by groue** [comment]
> The prompt attempts to insert the func start(i: _, onError: _, onChange: _) defined in the _ValueObservationProtocol. This protocol requirement appears to mirror a similar function in GRDB found in ValueObservation.swift which was updated with the release of 4.1.0 to no longer throw an error, which looks to have broken protocol conformance.

Your analysis is correct. This is technically a breaking change, but only when one depends on the exact method signature of ValueObservation, as RxGRDB does. Regular users of ValueObservation will just see warnings, which are not strictly speaking a breaking change. It was planning to release upgrades to both libraries at the same time, for a smooth transition, but I faced this CocoaPods issue.

**Comment by AndyHeardApps** [comment]
Thanks for the quick response. Shame it's all relying on a CocoaPods fix really.

**Comment by groue** [comment]
GRDB 4.1.1 and RxGRDB 0.15.0 have been released :-)
